name: aeki_appi
description: Flutter app for controlling your Äike T-scooter via Bluetooth.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^2.3.2
  flutter_blue_plus_winrt: ^0.0.20
  provider: ^6.1.2
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
